export enum KafkaSearchTopic {
  INDEX_NEW_COMMUNITY = 'INDEX_NEW_COMMUNITY',
  INDEX_UPDATE_COMMUNITY = 'INDEX_UPDATE_COMMUNITY',
  INDEX_DELETE_COMMUNITY = 'INDEX_DELETE_COMMUNITY',

  INDEX_NEW_POST = 'INDEX_NEW_POST',
  INDEX_UPDATE_POST = 'INDEX_UPDATE_POST',
  INDEX_DELETE_POST = 'INDEX_DELETE_POST',

  INDEX_NEW_COMMENT = 'INDEX_NEW_COMMENT',
  INDEX_UPDATE_COMMENT = 'INDEX_UPDATE_COMMENT',
  INDEX_DELETE_COMMENT = 'INDEX_DELETE_COMMENT',
}
export type IKafkaSearchTopic =
  | KafkaSearchTopic.INDEX_NEW_COMMUNITY
  | KafkaSearchTopic.INDEX_UPDATE_COMMUNITY
  | KafkaSearchTopic.INDEX_DELETE_COMMUNITY

  | KafkaSearchTopic.INDEX_NEW_POST
  | KafkaSearchTopic.INDEX_UPDATE_POST
  | KafkaSearchTopic.INDEX_DELETE_POST
  
  | KafkaSearchTopic.INDEX_NEW_COMMENT
  | KafkaSearchTopic.INDEX_UPDATE_COMMENT
  | KafkaSearchTopic.INDEX_DELETE_COMMENT;
